
package ru.lama;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "soap-proxy", targetNamespace = "http://www.lama.ru/test/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapProxy {


    /**
     * 
     * @param packet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.lama.ru/test/sendToJMS")
    @WebResult(name = "response", targetNamespace = "http://www.lama.ru/test/", partName = "response")
    public String sendToJMS(
        @WebParam(name = "packet", targetNamespace = "http://www.lama.ru/test/", partName = "packet")
        PacketType packet);

}
